authorName: default
experimentName: example_imagenet-network-morphism-test
trialConcurrency: 1
maxExecDuration: 12h
maxTrialNum: 6000
#choice: local, remote, pai
trainingServicePlatform: local
#searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, NetworkMorphism
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: NetworkMorphism
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    #for now, this tuner only supports cv domain
    task: cv
    #input image width
    input_width: 224
    #input image channel
    input_channel: 3
    #number of classes
    n_output_node: 1000
trial:
    command: NPU_NUM=1 \
             python3 imagenet_train.py \
             --slave 1 \
             --ip 127.0.0.1 \
             --batch_size 256 \
             --train_data_dir /home/ma-user/work/train/ \
             --val_data_dir /home/ma-user/work/val/ \
             --epochs 60 \
             --warmup_1 2 \   
             --warmup_2 30 \   
             --warmup_3 45
             
    codeDir: .
    gpuNum: 0
