authorName: default
experimentName: example_imagenet-network-morphism-test
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 6000
#choice: local, remote, pai
trainingServicePlatform: local
#searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, NetworkMorphism
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: NetworkMorphism
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    #for now, this tuner only supports cv domain
    task: cv
    #input image width
    input_width: 224
    #input image channel
    input_channel: 3
    #number of classes
    n_output_node: 1000
trial:
    command: NPU_NUM=${AIPERF_NPU_NUM_PER_NODE} \
             OBSHOME=obs://${AIPERF_OBS_WORKDIR}/runlog \
             python3 imagenet_train.py \
             --slave 1 \
             --ip ${AIPERF_MASTER_IP} \
             --batch_size 256 \
             --train_data_dir /home/ma-user/modelarts/inputs/data_0/train/ \
             --val_data_dir /home/ma-user/modelarts/inputs/data_0/val/ \
             --epochs 150 \
             --warmup_1 150 \   
             --warmup_2 150 \   
             --warmup_3 150
             
    codeDir: .
    gpuNum: 0
