authorName: default
experimentName: example_imagenet-network-morphism-test
trialConcurrency: 1
maxExecDuration: 3h
maxTrialNum: 6
trainingServicePlatform: local
useAnnotation: false
logLevel: trace
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, NetworkMorphism
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: NetworkMorphism
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    #for now, this tuner only supports cv domain
    task: cv
    #input image width
    input_width: 224
    #input image channel
    input_channel: 3
    #number of classes
    n_output_node: 1000
trial:
  command: CUDA_VISIBLE_DEVICES=0 \
           python3 imagenet_train.py \
           --slave 1 \
           --ip 172.23.33.30 \
           --batch_size 48 \
           --warmup_1 1 --warmup_2 2 --warmup_3 3 --epoch 10 \
           --initial_lr 1e-1 \
           --final_lr 0 \
           --num_parallel_calls 10 \
           --train_data_dir /mnt/zoltan/public/dataset/final/train/ \
           --val_data_dir /mnt/zoltan/public/dataset/final/val/ 

  codeDir: .
  gpuNum: 0
